name: Manual Package

on:
  workflow_dispatch:

jobs:

  Build:

    name: Build
    runs-on: windows-2019

    steps:

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.7'

      - name: Set Git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Clone PyInstaller source
        uses: actions/checkout@v2
        with:
          repository: 'pyinstaller/pyinstaller'
          ref: 'v4.5.1'
          path: './pyinstaller'

      - name: Build PyInstaller bootloader
        run: |
          cd ./pyinstaller/bootloader
          python ./waf all --target-arch=64bit

      - name: Install PyInstaller
        run: |
          cd ./pyinstaller
          python -m pip install wheel
          python setup.py install

      - name: Clone repo
        uses: actions/checkout@v2
        with:
          path: './Spicetify-Easyinstall'

      - name: Build
        run: |
          cd .\Spicetify-Easyinstall
          python -m pip install -r requirements.txt
          pyinstaller --clean -y --dist dist\windows --workpath tmp build.spec

      - name: Cleanup + Include .py files
        shell: cmd
        run: |
          cd      .\Spicetify-Easyinstall
          del  /f dist\windows\Spicetify-Easyinstall\opengl32sw.dll
          del  /f dist\windows\Spicetify-Easyinstall\Qt5DBus.dll
          del  /f dist\windows\Spicetify-Easyinstall\Qt5Network.dll
          del  /f dist\windows\Spicetify-Easyinstall\Qt5Qml.dll
          del  /f dist\windows\Spicetify-Easyinstall\Qt5QmlModels.dll
          del  /f dist\windows\Spicetify-Easyinstall\Qt5Quick.dll
          del  /f dist\windows\Spicetify-Easyinstall\Qt5Svg.dll
          del  /f dist\windows\Spicetify-Easyinstall\Qt5WebSockets.dll
          mkdir   dist\windows\Spicetify-Easyinstall\lib
          move /y dist\windows\Spicetify-Easyinstall\aiohttp            dist\windows\Spicetify-Easyinstall\lib
          move /y dist\windows\Spicetify-Easyinstall\multidict          dist\windows\Spicetify-Easyinstall\lib
          move /y dist\windows\Spicetify-Easyinstall\yarl               dist\windows\Spicetify-Easyinstall\lib
          move /y dist\windows\Spicetify-Easyinstall\*.pyd              dist\windows\Spicetify-Easyinstall\lib
          move /y dist\windows\Spicetify-Easyinstall\api-ms-win-*       dist\windows\Spicetify-Easyinstall\lib
          move /y dist\windows\Spicetify-Easyinstall\d3dcompiler_47.dll dist\windows\Spicetify-Easyinstall\lib
          move /y dist\windows\Spicetify-Easyinstall\libcrypto-1_1.dll  dist\windows\Spicetify-Easyinstall\lib
          move /y dist\windows\Spicetify-Easyinstall\libEGL.dll         dist\windows\Spicetify-Easyinstall\lib
          move /y dist\windows\Spicetify-Easyinstall\libffi-7.dll       dist\windows\Spicetify-Easyinstall\lib
          move /y dist\windows\Spicetify-Easyinstall\libGLESv2.dll      dist\windows\Spicetify-Easyinstall\lib
          move /y dist\windows\Spicetify-Easyinstall\libssl-1_1.dll     dist\windows\Spicetify-Easyinstall\lib
          move /y dist\windows\Spicetify-Easyinstall\MSVCP140_1.dll     dist\windows\Spicetify-Easyinstall\lib
          move /y dist\windows\Spicetify-Easyinstall\MSVCP140.dll       dist\windows\Spicetify-Easyinstall\lib
          move /y dist\windows\Spicetify-Easyinstall\ucrtbase.dll       dist\windows\Spicetify-Easyinstall\lib
          move /y dist\windows\Spicetify-Easyinstall\VCRUNTIME140_1.dll dist\windows\Spicetify-Easyinstall\lib
          move /y dist\windows\Spicetify-Easyinstall\VCRUNTIME140.dll   dist\windows\Spicetify-Easyinstall\lib
          mkdir   dist\windows\Spicetify-Easyinstall\modules
          copy /y Spicetify-Easyinstall.py                              dist\windows\Spicetify-Easyinstall
          copy /y requirements.txt                                      dist\windows\Spicetify-Easyinstall
          copy /y modules                                               dist\windows\Spicetify-Easyinstall\modules

      - name: Get short SHA string
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 7

      - name: Zip package
        shell: cmd
        run: 7z a -r .\Spicetify-Easyinstall-manual-${{ steps.short-sha.outputs.sha }}.zip .\Spicetify-Easyinstall\dist\windows\Spicetify-Easyinstall\*

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Spicetify-Easyinstall-manual-${{ steps.short-sha.outputs.sha }}
          path: ./Spicetify-Easyinstall-manual-${{ steps.short-sha.outputs.sha }}.zip

      - name: Purge old artifacts
        uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 0
