name: Build Release Package

on:
  release:
    types: [ published ]

jobs:

  Build:

    name: Build
    runs-on: windows-2019

    steps:

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.7'

      - name: Set Git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Clone PyInstaller source
        uses: actions/checkout@v2
        with:
          repository: 'pyinstaller/pyinstaller'
          ref: 'v4.5.1'
          path: './pyinstaller'

      - name: Build PyInstaller bootloader
        run: |
          cd ./pyinstaller/bootloader
          python ./waf all --target-arch=64bit

      - name: Install PyInstaller
        run: |
          cd ./pyinstaller
          python -m pip install wheel
          python setup.py install

      - name: Clone repo
        uses: actions/checkout@v2
        with:
          path: './roblox-random-game'

      - name: Build
        run: |
          cd .\roblox-random-game
          python -m pip install -r requirements.txt
          pyinstaller --clean -y --dist dist\windows --workpath tmp build.spec

      - name: Cleanup + Include .py files
        shell: cmd
        run: |
          cd      .\roblox-random-game
          del  /f dist\windows\roblox-random-game\opengl32sw.dll
          del  /f dist\windows\roblox-random-game\Qt5DBus.dll
          del  /f dist\windows\roblox-random-game\Qt5Network.dll
          del  /f dist\windows\roblox-random-game\Qt5Qml.dll
          del  /f dist\windows\roblox-random-game\Qt5QmlModels.dll
          del  /f dist\windows\roblox-random-game\Qt5Quick.dll
          del  /f dist\windows\roblox-random-game\Qt5Svg.dll
          del  /f dist\windows\roblox-random-game\Qt5WebSockets.dll
          mkdir   dist\windows\roblox-random-game\lib
          move /y dist\windows\roblox-random-game\aiohttp            dist\windows\roblox-random-game\lib
          move /y dist\windows\roblox-random-game\multidict          dist\windows\roblox-random-game\lib
          move /y dist\windows\roblox-random-game\yarl               dist\windows\roblox-random-game\lib
          move /y dist\windows\roblox-random-game\*.pyd              dist\windows\roblox-random-game\lib
          move /y dist\windows\roblox-random-game\api-ms-win-*       dist\windows\roblox-random-game\lib
          move /y dist\windows\roblox-random-game\d3dcompiler_47.dll dist\windows\roblox-random-game\lib
          move /y dist\windows\roblox-random-game\libcrypto-1_1.dll  dist\windows\roblox-random-game\lib
          move /y dist\windows\roblox-random-game\libEGL.dll         dist\windows\roblox-random-game\lib
          move /y dist\windows\roblox-random-game\libffi-7.dll       dist\windows\roblox-random-game\lib
          move /y dist\windows\roblox-random-game\libGLESv2.dll      dist\windows\roblox-random-game\lib
          move /y dist\windows\roblox-random-game\libssl-1_1.dll     dist\windows\roblox-random-game\lib
          move /y dist\windows\roblox-random-game\MSVCP140_1.dll     dist\windows\roblox-random-game\lib
          move /y dist\windows\roblox-random-game\MSVCP140.dll       dist\windows\roblox-random-game\lib
          move /y dist\windows\roblox-random-game\ucrtbase.dll       dist\windows\roblox-random-game\lib
          move /y dist\windows\roblox-random-game\VCRUNTIME140_1.dll dist\windows\roblox-random-game\lib
          move /y dist\windows\roblox-random-game\VCRUNTIME140.dll   dist\windows\roblox-random-game\lib
          mkdir   dist\windows\roblox-random-game\modules
          copy /y main.py                              dist\windows\roblox-random-game
          copy /y requirements.txt                                      dist\windows\roblox-random-game

      - name: Zip package
        shell: cmd
        run: 7z a -r .\roblox-random-game-v${{ github.event.release.tag_name }}.zip .\roblox-random-game\dist\windows\roblox-random-game\*

      - name: Publish package
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./roblox-random-game-v${{ github.event.release.tag_name }}.zip

      - name: Purge old artifacts
        uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 0

      - name: Delete skipped workflow runs
        uses: Willy-JL/delete-skipped-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 0
